### PR TITLE
remove trailing whitespace

### PR DESCRIPTION
**Pull request by boegel**
for some reason, there's a lot of trailing whitespace in the easyconfigs you contributed via https://github.com/hpcugent/easybuild-easyconfigs/pull/3449, any idea why?

This is annoying since it screws around with our review process (`eb --review-pr`).

This PR cleans up that trailing whitespace, please include this in your branch?

### CODE REVIEW

**Comment by AFCJamie** [comment]
I'm not sure what you mean by 'trailing whitespace'? The last line in the easyconfigs that I can see are the 'moduleclass = x' lines, unless I should also be taking out the whitespace in between lines? Sorry for the hassle this is causing.

**Comment by boegel** [comment]
@AFCJamie several of the lines end with an extra space, maybe your editor configuration is causing this?

**Comment by boegel** [comment]
@AFCJamie clearly visible in the diff at https://github.com/AFCJamie/easybuild-easyconfigs/pull/1/files

**Comment by AFCJamie** [comment]
Ohh, I see what you mean now. I'll look at fixing that now.

**Pull request merged**
